[build]
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[scheduled.functions]]
  name = "scheduler"
  cron = "*/5 * * * *"

[build.environment]
  NODE_VERSION = "20"